name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          # Your GitHub username
          user: jg-eno
          # Base content (will appear in root, header, activity, community, repositories, metadata)
          base: "header, repositories"
          # Plugin - ISO calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # Plugin - Most used languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          # Plugin - GitHub habits
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: America/Sao_Paulo
          commits_authoring: jg-eno
          filename: github-metrics.svg
          output_action: commit
          committer_message: "chore: update metrics"
